name: hoyo_launcher
description: Showcase App for Windows UI for Flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  system_theme: ^2.3.1
  window_manager: ^0.3.0
  flutter_acrylic: ^1.0.0+2
  url_launcher: ^6.1.7
  http: ^1.1.0
  intl: ^0.18.1
  google_fonts: ^6.1.0
  fluent_ui: ^4.8.2
  file_picker: ^6.1.1
  injectable: ^2.3.2
  hive: ^2.2.3
  get_it: ^7.6.4
  freezed_annotation: ^2.4.1
  package_info_plus: ^5.0.1
  json_annotation: ^4.8.1
  path: ^1.8.3
  path_provider: ^2.1.1
  drift: ^2.3.0                        #数据库
  sqlite3_flutter_libs: ^0.5.12
  extended_image: ^8.0.1               #图片
  sqlite_viewer: ^1.0.5
  flutter_svg: ^2.0.9
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.1.6
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  injectable_generator: ^2.1.5    # 依赖注入代码生成
  json_serializable: ^6.7.1       # json 序列化代码生成
  freezed: ^2.3.2
  drift_dev: ^2.3.2
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.3.2

flutter_gen:
  output: lib\presentation\gen # Optional (default: lib/gen/)
  line_length: 120 # Optional (default: 80)
  assets:
    outputs:
      style: camel-case
      class_name: R
    
  
  # Optional
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets\fonts\BebasNeue.ttf
    - family: Manrope
      fonts:
        - asset: assets\fonts\Manrope.ttf
    - family: RobotoMono
      fonts:
        - asset: assets\fonts\RobotoMono.ttf
    - family: Teko
      fonts:
        - asset: assets\fonts\.ttf

flutter_native_splash:
  color: "#000000"
  image: assets/logo.png